### ISSUE TITLE
Initial TOC links have a slash (/) in the url, causing 404's

### ISSUE THREAD

**Issue by jwold** [xwp/engineering-best-practices#16]
The first 3 links in the Table of Contents on the Home page are leading to 404 pages. This is because the links have a (/) prior to the # tag. 

The file update-toc.php needs to be updated to add a conditional (or something like that) that will remove the (/) in cases where the link simply points to an anchor on the page.

**Comment by valendesigns** [comment]
I believe having a trailing slash is the correct approach here. However, leaving out the `engineering-best-practices` segment from the path is what's causing the 404's.

**Comment by jwold** [comment]
Good point! I think that makes sense.

**Comment by derekherman** [comment]
Docs have been moved to Gitbook and updated.
