### ISSUE TITLE
Grammar in Project Structure > Modular Code > Themes

### ISSUE THREAD

**Issue by jwold** [xwp/engineering-best-practices#18]
In order to modify this run-on sentence, my suggestion is that we change:

<p>Take a look at our <a href="https://github.com/xwp/config-driven-wp">Config-Driven WP</a> project for some (dated) examples for a common approach we take for normalizing the theme's configuration into a <a href="https://github.com/xwp/config-driven-wp/blob/master/docroot/wp-content/themes/radio/config.php"><code>config.php</code></a> array which then be cleanly merged with a child theme's configuration array.</p>

to:

<p>Take a look at our <a href="https://github.com/xwp/config-driven-wp">Config-Driven WP</a> project for some (dated) examples of a common approach we take at normalizing the theme's configuration into a <a href="https://github.com/xwp/config-driven-wp/blob/master/docroot/wp-content/themes/radio/config.php"><code>config.php</code></a> array. The config array can then be cleanly merged with a child theme's configuration array.</p>

**Comment by westonruter** [comment]
@jwold Thanks! You should be able to make this change directly via https://github.com/xwp/engineering-best-practices/edit/gh-pages/_includes/markdown/Structure.md
