### ISSUE TITLE
Recommend use of WP Utils for Ajax in the admin

### ISSUE THREAD

**Issue by westonruter** [xwp/engineering-best-practices#7]
JS should use `wp.ajax.send()` when possible.

https://xwp.github.io/engineering-best-practices/javascript/

**Comment by westonruter** [comment]
Also, we should not be using `admin-ajax.php` on frontend requests. See internal discussion at https://xwp.slack.com/archives/watercooler/p1446229103000380

**Comment by derekherman** [comment]
New docs have been added here https://docs.xwp.co/engineering-best-practices/languages/php#ajax-endpoints
